#!/bin/bash

source $(dirname $0)/d-conf

XPOS=$(( $(xdotool getmouselocation | awk -F " " '{print $1}' | cut -d ":" -f 2) - 20 ))
HEIGHT="13"
WIDTH="104"
LINES="3"
ALIGN="left"

id=$(iwconfig wlan0 2> /dev/null | grep ESSID | awk -F\" '{print $2}')
if [ "$id" = "" ]; then
	essid="^fg($FG2)ESSID: ^fg($FG1)not connected"
elif [ "$id" != "" ]; then
	essid="^fg($FG2)ESSID: ^fg($FG1)$id"
fi

signal=$(iwconfig wlan0 2> /dev/null | awk -F= '/Quality/ {print $3}' | awk '{print $1 $2}')
if [ "$signal" = "" ]; then
	strength="^fg($FG2)Strength: ^fg($FG1)no signal"
elif [ "$signal" != "" ]; then
	strength="^fg($FG2)Strength: ^fg($FG1)$signal"
fi

tun=$(netstat -atn | grep ":11590")
if [ "$tun" == "" ]; then
	tunnel="^fg($FG2)Tunnel status: ^fg($FG1)off"
else
	tunnel="^fg($FG2)Tunnel status: ^fg($FG1)on"
fi


(echo "^fg($red) Network"; echo "$essid"; echo "$strength"; echo "$tunnel"; sleep $TIMING) | dzen2 -bg $BG -fn $FONT -x $XPOS -y $YPOS -w $WIDTH -h $HEIGHT -l $LINES -e 'onstart=uncollapse;button1=exit;button2=exit;button3=exit;button4=exit'
